include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v23.0.1

variables:
  AUTO_DEVOPS_KANIKO: "✔️"
  AUTO_DEVOPS_RELEASE_AUTO: "✔️"
  AUTO_DEVOPS_PRODUCTION_AUTO: "✔️"
  AUTO_DEVOPS_ENABLE_KAPP: "✔️"
  AUTO_DEVOPS_TEST_DISABLED: "🛑"
  AUTO_DEVOPS_QUALITY_DISABLED: "🛑"
  AUTO_DEVOPS_NOTIFY_DISABLED: "🛑"

Build:
  stage: Code Quality
  script:
    - echo "No build, ma"
