plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - README.md
      message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
repositoryUrl: ssh://git@gitlab.factory.social.gouv.fr:443/SocialGouv/covid.git
