name: Deactivate

on:
  pull_request:
    types: [ closed ]
    
jobs:
  bury_review_env:
    name: 🪦 Review
    runs-on: ubuntu-latest
    steps:
    - uses: SocialGouv/actions/k8s-funeral@v1
      with:
        kube-config: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_DEV  }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
